### ISSUE TITLE
After saving a file CSV headers are moving from the first line to the middle of the file

### ISSUE THREAD

**Issue by szaboat** [prezi/plotserver#1]
https://plot.prezi.com/szaboat/points_by_user.csv

```
Week,Ati,Balazs,Csaba,Laci,Pepe
41,3,6,9,0,0
42,7,0,0,0,0
43,6,1,7,0,0
44,3,0,1,0,0
45,4,0,22,0,0
46,5,0,0,0,0
47,6,0,0,0,0
48,8,4,5,0,0
49,0,0,12,0,0
50,14,7,11,0,0
51,6,7,0,11,3
```

after save will become

```
41,3,6,9,0,0
42,7,0,0,0,0
43,6,1,7,0,0
44,3,0,1,0,0
45,4,0,22,0,0
46,5,0,0,0,0
Week,Ati,Balazs,Csaba,Laci,Pepe
47,6,0,0,0,0
48,8,4,5,0,0
49,0,0,12,0,0
50,14,7,11,0,0
51,6,7,0,11,3
```

Here is the result of the tangled file

![screen shot 2013-12-23 at 12 22 13 pm](https://f.cloud.github.com/assets/57303/1800407/988d37d8-6bc4-11e3-945f-7a49e05a5679.png)

**Comment by zoltanctoth** [comment]
headers are not supported in plotserver. Hit it with the headerless raw data!
